language:
  - java

jdk:
  - oraclejdk8

os:
  - linux

script:
  #if there is no scripts in the build section, by default ant will be run
  - ./build_script.sh
  
# after_success:
#   - bash <(curl -s https://codecov.io/bash)

